### ISSUE TITLE
Support .NET 7 `AndroidJavaSource`

### ISSUE THREAD

**Issue by gitlsl** [UlyssesWu/XamarinPosed#5]
老哥这个项目不知道还有在用吗。。 现在都是基于 LSPosed /ZYGISK的

**Comment by UlyssesWu** [comment]
暂时还没用.NET 7。到时候如果有问题会再适配一下，应该不会有太大的变化。
xposed模块不管是在VXP,LSP,还是我在readme中提到的Xpatch，基本上都是通用的。

**Comment by UlyssesWu** [comment]
https://github.com/UlyssesWu/XamarinPosed.Core
现已支持.NET 7，并在ZYGISK上测试通过（升级Magisk差点给我手机干废了，线刷救回来了）。

很遗憾.NET 7新增的`AndroidJavaSource`引用Java源码机制是用不了的（不能import mono.android），所以还是与现在差不多的实现方式，毕竟能用就行。
